### ISSUE TITLE
Related objects

### ISSUE THREAD

**Issue by tkoopa** [hiboutik/hiboutikapi#11]
Referring to your answer on https://github.com/hiboutik/hiboutikapi/issues/6 I see v2 is out but it doesn't look like related objects are part of the update, have I missed something or didn't it make it the release ?

**Comment by hiboutik** [comment]
Hi, as your issue is not related to this repo please contact directly Hiboutik's client service [here](https://www.hiboutik.com/en/contact/) or from your Hiboutik account.
Many variables may impact your results from the Hiboutik API (user rights, free vs premium options, account settings etc.)

Best regards
