### ISSUE TITLE
Missing a method to retrieve images

### ISSUE THREAD

**Issue by tkoopa** [hiboutik/hiboutikapi#5]
By calling the products/{id} method the returned object contains the urls of the products image, however these are not public so there is no way of retrieving. 
A method that allows retrieving the image in binary format would de useful to be to display a shop's product list for example

**Comment by hiboutik** [comment]
Hi,

As this could be very bandwidth consuming, the route is not public.
Send us a message from your account and we will provide you with the correct route.
You will only be able to fetch 100x100 pixels images.
Keep in mind that the standard monthly limit for API calls is 10000 per account.

Sincerely
Guillaume

**Comment by Agence-Spritz** [comment]
Hi, I plan to create a website that is able to query the Hiboutik product base of one of my clients using Hiboutik, in order to display their products on the site. It seems possible using the API.
Is it possible to retrieve the URL of the product images? I'll need to display product images in correct quality (1000x1000) for each product. Can you help me on this point please?
